### ISSUE TITLE
Add merge sort algorithm

### ISSUE THREAD

**Issue by IamEzio** [shreeshailaya/C-DAC-Notes#102]
Hi! @shreeshailaya I would like to add Merge sort algorithm in Java under the C-DAC-Notes/Data structure/Sorting/Sorting/src folder if it's not already added somewhere else.

**Comment by shreeshailaya** [comment]
@IamEzio can I assign you another task, pretty easy...

**Comment by shreeshailaya** [comment]
@IamEzio [can you do this?](https://github.com/shreeshailaya/C-DAC-Notes/issues/109)
