### ISSUE TITLE
Write the documentation on hash and hash map of data strecture

### ISSUE THREAD

**Issue by shreeshailaya** [shreeshailaya/C-DAC-Notes#107]
here is the Hash/HashMapDay14 1/7 [Readme.md](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Data%20structure#day-14-17hashtime-complixitykruskal-algorithmprimes-algoavl-tree-balanced-factor) you need to provide the notes regarding this, you can put gifs or images so the user can understand how exactly the hashing algorithms work also write some code snippets for understanding, following are the points which must be covered.

- Image for an explanation of how hash/hash map works
- Code snippet 

Note:- if you want to add media(image/gifs/png) keep them in[ C-DAC-Notes/Data structure/Media/](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Data%20structure/Media)

External Referanc Links [javatpoint](https://www.javatpoint.com/daa-hashing), [geeksforgeeks ](https://www.geeksforgeeks.org/hashing-in-java/)

**Comment by SnehaNarendran01071998** [comment]
I would like to work on this. Can I be assigned to this?
