### ISSUE TITLE
create a new project of sorting algorithms

### ISSUE THREAD

**Issue by shreeshailaya** [shreeshailaya/C-DAC-Notes#109]
here are the sorting algorithms [assignments](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Data%20structure/Sorting) there are two projects and some other RAR files you have to create one single project which contains all of the sorting algorithms which are mentioned in the [readme.md](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Data%20structure#sorting) of data structure.

Note: all the sorting algorithms are present in assignments or in RAR you have to unzip them or check them merge them into one single project called Sorting Algorithms. (don't remove anything just make a new project)

**Comment by IamEzio** [comment]
@shreeshailaya, I had two small doubts -
1. I couldn't find the location of merge sort and shell sort. If they are not present should I add them by my own or are you going to create an issue for it?
2. I have moved all currently present algorithms into src directory of single sorting project. Should I delete " Sorting Algorithms-1 " project and " Sorting(1).rar " file or leave them as it is?

Sorting project looks something like this now : 
![sortingDirecrtory](https://user-images.githubusercontent.com/89375125/138257707-dbadb5a1-9a59-4155-8e6b-d501d07eb37c.png)
