### ISSUE TITLE
Write notes about Time and Space Complexity in Data Structure

### ISSUE THREAD

**Issue by shreeshailaya** [shreeshailaya/C-DAC-Notes#115]
here is the Time Complexity Day14 1/7 [Readme.md](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Data%20structure#time-complixity) you need to provide the notes regarding time complexity as well as space complexity, you can put gifs or images so the user can understand how exactly the time complexity work also write some code snippets for understanding, following are the points which must be covered.

- Image for an explanation of how time and space complexity works(eg. graphs)
- Code snippet 

Note:- if you want to add media(image/gifs/png) keep them in[ C-DAC-Notes/Data structure/Media/](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Data%20structure/Media)

External Referanc Links [geeksforgeeks-space complexity](https://www.geeksforgeeks.org/g-fact-86/), [geeksforgeeks-time complexity ](https://www.geeksforgeeks.org/understanding-time-complexity-simple-examples/)

- Check spelling's too

**Comment by shreeshailaya** [comment]
#127 complete its time complexity now need to add space complexity.

**Comment by SabujGolui** [comment]
can you please assign it to me, I can help you to write the notes.
