### ISSUE TITLE
Design a proper syllabus content for the OS

### ISSUE THREAD

**Issue by shreeshailaya** [shreeshailaya/C-DAC-Notes#116]
Design a Syllabus for Operating System and put the content or content name sequence in [C-DAC-Notes/Operating system/Readme.md](C-DAC-Notes/Operating system/Readme.md) 

- Example
 Introduction to OS, Introduction to Linux, Shell Programming, Processes, Signals, Threads, Memory, management, Virtual Memory, Deadlock, Inter-process communication, etc

**Comment by PurviSaini** [comment]
Can I work on this issue?

**Comment by PurviSaini** [comment]
I need to mention only the topics or the explanation along with the each of the topic?

**Comment by shreeshailaya** [comment]
@PurviSaini for now, mention major topics in the h2(i.e ##) tag and sub-topic (if there is any) in the h3(i.e ###) tag... after this if you wish to complete them create a new issue...

**Comment by PurviSaini** [comment]
Okay, Thanks for the clarification.
I am on it.

**Comment by shreeshailaya** [comment]
#133 PR Resolved this ticket Thank You Purvi...
