### ISSUE TITLE
19June Searching Assignments

### ISSUE THREAD

**Issue by shreeshailaya** [shreeshailaya/C-DAC-Notes#12]
Assignments Incomplete [19june Searching](https://github.com/shreeshailaya/c-dac/tree/main/Data%20structure/19juneDay4)

**Comment by shikhar13012001** [comment]
Hi I would like to work on this. Can I submit my codes in CPP ?

**Comment by shreeshailaya** [comment]
@shikhar13012001 No the required DS code should be in java

**Comment by shikhar13012001** [comment]
Ok sir I know Java as well , can I work on this ? Could you assign it to me ?

**Comment by shikhar13012001** [comment]
Sir, Do we have to optimize the code's time complexity or we can use simple brute force as well ?

**Comment by shreeshailaya** [comment]
@shikhar13012001  Consider time complexity, but your goal should be working code for the given problem statement.
