### ISSUE TITLE
Delete appitude folder from notes

### ISSUE THREAD

**Issue by shreeshailaya** [shreeshailaya/C-DAC-Notes#125]
delete [appitude](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Appitude) folder from notes ...

**Comment by iatharva** [comment]
Hi, Can I work on this? Can you assign this to me?

**Comment by shreeshailaya** [comment]
he @iatharva you can check another issue or create your own, @prayatharth already makes PR
