### ISSUE TITLE
Check all spelling and typo in core java folder main readme.md

### ISSUE THREAD

**Issue by shreeshailaya** [shreeshailaya/C-DAC-Notes#128]
Check all spelling and typos in the [Core Java](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Core%20Java) folder main [readme.md](https://github.com/shreeshailaya/C-DAC-Notes/blob/main/Core%20Java/README.md) you can also check for small typos in it.

**Comment by ManasviGoyal** [comment]
I would like to work on it

**Comment by semnim** [comment]
Is this about the readme.md only or about all subfolders of the Core Java folder?

**Comment by shreeshailaya** [comment]
@semnim only for the core java folder readme but @ManasviGoyal already take this task you can check another issue else create your own ...
