### ISSUE TITLE
Complete 5 points in notes with a proper diagram and example of Operating system.

### ISSUE THREAD

**Issue by shreeshailaya** [shreeshailaya/C-DAC-Notes#134]
Complete the notes in the Operating system folder(the first five listed below) for that you have to make changes in[ Operating system/readme.md](https://github.com/shreeshailaya/C-DAC-Notes/blob/main/Operating%20system/Readme.md).
You have to complete 
- MultiProgramming
- MultiProcessing
- MultiTasking
- Multithreading

Take reference from internet
Note: If there are images in notes please kept them in the [Operating system/media](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Operating%20system/Media) folder.

**Comment by santhos-13** [comment]
Hi @shreeshailaya, Can you assign this to me? i will give a PR by tomorrow..

**Comment by santhos-13** [comment]
Hi @shreeshailaya , I gave PR #149 .
