### ISSUE TITLE
25-26 june Day9-10 documentation and code

### ISSUE THREAD

**Issue by shreeshailaya** [shreeshailaya/C-DAC-Notes#14]
the whole day 25-26 june day 9-10 [ documentation](https://github.com/shreeshailaya/c-dac/tree/main/Data%20structure#day-9-256) and  [assignments](https://github.com/shreeshailaya/c-dac/tree/main/Data%20structure) with media pending

**Comment by Rakhipujari** [comment]
Hi @shreeshailaya,
I would like to add documentation and assignments for the day 25-26 June by adding double ended queue and priority queue concepts. Please assign this issue to me.

**Comment by Rakhipujari** [comment]
Hi @shreeshailaya,
Can you please add Hacktoberfest label to the issue as I am participating under Hacktoberfest 2024.

**Comment by shreeshailaya** [comment]
Done @Rakhipujari

**Comment by Rakhipujari** [comment]
Hi @shreeshailaya,
I have already added the required documentation and assignments along with the media and made PR. Please approve it.
