### ISSUE TITLE
kruskal Algorithm

### ISSUE THREAD

**Issue by shreeshailaya** [shreeshailaya/C-DAC-Notes#142]
here is the Kruskal Algorithm Day14 1/7 [Readme.md](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Data%20structure#kruskal-algorithm) you need to provide the notes regarding Kruskal Algorithm, you can put gifs or images so the user can understand how exactly the Kruskal Algorithm work also write some code snippets for understanding(in java), following are the points which must be covered.

- Image for an explanation of how Kruskal Algorithm works
- Code snippet

Note:- if you want to add media(image/gifs/png) keep them in[ C-DAC-Notes/Data structure/Media/](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Data%20structure/Media)

External Reference Links [Kruskal Algorithm](https://www.javatpoint.com/kruskal-algorithm-java)

**Comment by manish-singh-bisht** [comment]
Hey @shreeshailaya  where to add these notes?
Please assign me , I want to work in this project of yours.
Thank you

**Comment by manish-singh-bisht** [comment]
Hey @shreeshailaya in which file do I have to make the changes?

**Comment by manish-singh-bisht** [comment]
Hey @shreeshailaya  I am sorry ,I wont be able to do this.

**Comment by Debarpan08** [comment]
@shreeshailaya ,Would you please assign this to me?

**Comment by Aanya9693** [comment]
@shreeshailaya  Hey! I would like to solve this issue, Can you assign this to me?

**Comment by shreeshailaya** [comment]
@Aanya9693 direct open PR

**Comment by MrJayendra** [comment]
I am interested in this work.
Please assign it to me.

**Comment by shreeshailaya** [comment]
#143  fixed
