### ISSUE TITLE
Complete Bubble Sort In Data Structure

### ISSUE THREAD

**Issue by shreeshailaya** [shreeshailaya/C-DAC-Notes#144]
here is the bubble sort [Readme.md](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Data%20structure#buebble-sort) you need to provide the notes regarding bubble sort, you can put gifs or images so the user can understand how exactly the bubble sort work also write some code snippets for understanding(in java), following are the points which must be covered.

- Image for an explanation of how bubble sort works
- Code snippet

**Comment by ProtyayMnd50** [comment]
could you assign it to me @shreeshailaya pls?

**Comment by thechangamunda** [comment]
It's my first time contributing in hacktoberfest, assign this to me!

**Comment by shreeshailaya** [comment]
@all please open PR directly...

**Comment by santhos-13** [comment]
@shreeshailaya could you add hacktoberfest label to the issue

**Comment by santhos-13** [comment]
@shreeshailaya and the pull request file must be in readme.md ?

**Comment by santhos-13** [comment]
Hi @shreeshailaya , i added the BubbleSort algo to Datastructure ReadMe file. And gave a PR #145 .Kindly accept the PR. Thank You

**Comment by ba-p** [comment]
!assign

**Comment by Rohit-R2000** [comment]
sir i can provide an brief pictorial explanation on bubble short with its iterative code.  so can you please assign this to me

**Comment by shreeshailaya** [comment]
@Rohit-R2000 because too many people want to make contribute please open PR directly I cannot assign a single issue to multiple people...
