### ISSUE TITLE
Correct the Operating System Notes multithreading_01.jpg URL

### ISSUE THREAD

**Issue by shreeshailaya** [shreeshailaya/C-DAC-Notes#152]
Correct the Operating System Notes ([Readme.md](https://github.com/shreeshailaya/C-DAC-Notes/blob/main/Operating%20system/Readme.md)) multithreading_01.jpg URL

- Correct URL (https://github.com/shreeshailaya/C-DAC-Notes/blob/main/Operating%20system/Media/multithreading_01.jpg)
-  Wrong URL (https://github.com/shreeshailaya/C-DAC-Notes/blob/main/Operating%20system/Media/multithreading_01.png)

**Comment by santhos-13** [comment]
assign it to me @shreeshailaya

**Comment by santhos-13** [comment]
#155
