### ISSUE TITLE
Remove bad links from Data Structure notes 

### ISSUE THREAD

**Issue by shreeshailaya** [shreeshailaya/C-DAC-Notes#154]
Remove the user (Bl****99) user branch image link and replace it with the main project main branch...

**Comment by santhos-13** [comment]
@shreeshailaya 
is this what need to be done?
wrong link :
(https://raw.githubusercontent.com/Blaize99/C-DAC-Notes/main/Data%20structure/Media/ka-1.webp)

correct link:
(https://raw.githubusercontent.com/shreeshailaya/C-DAC-Notes/main/Data%20structure/Media/ka-1.webp)
