### ISSUE TITLE
Check broken links and fix them.

### ISSUE THREAD

**Issue by shreeshailaya** [shreeshailaya/C-DAC-Notes#172]
<img width="662" alt="image" src="https://github.com/shreeshailaya/C-DAC-Notes/assets/35342628/2aaf0e13-bced-4c38-8df7-257ddbf83cf5">

**Comment by a6ar55** [comment]
Hey,  can I work on it

**Comment by shreeshailaya** [comment]
Go a head @a6ar55

**Comment by readyready15728** [comment]
I wrote a _very_ quick and dirty Python script to look for links that return code 404, intended to be run at the root directory of the project:

https://gist.github.com/readyready15728/f3749e6cfd788fae8d24041a26c7e4a7

It reports 3 broken links and all are false positives (ended with a period, which the Markdown parser takes care of).

**Comment by techieadi4703** [comment]
hey @shreeshailaya , I'm interested in this issue can you assign me this issue to me.

**Comment by shreeshailaya** [comment]
This isssue has been Resolved
