### ISSUE TITLE
Calculator Project using Python

### ISSUE THREAD

**Issue by DevDatir** [shreeshailaya/C-DAC-Notes#177]
Hey,

I would love to contribute to this repo, please assign me this issue @shreeshailaya !
Can you please assign this to me under the hacktoberfest2024 tag?

**Comment by shreeshailaya** [comment]
Hello @DevDatir could you please take a look on pending issue or describe your issue more like where you want to put your calculator project in which language it is build on?

**Comment by DevDatir** [comment]
Hey,
I am willing to add a basic Python project that performs essential arithmetic operations while showcasing GUI development skills using Tkinter. I want to add this under python projects in the python folder.

**Comment by shreeshailaya** [comment]
Hello @DevDatir 
Add new folder under  Python/Assignments called **Projects** and add your code there.
Folder Strecure : Python/Assignments/Projects

**Comment by DevDatir** [comment]
Please review this PR - #183

**Comment by DevDatir** [comment]
@shreeshailaya may I know what I did wrong?
