### ISSUE TITLE
Change the Template of firstPRMergeComment 

### ISSUE THREAD

**Issue by shreeshailaya** [shreeshailaya/C-DAC-Notes#179]
Change the replay message by the action of firstPRMergeComment 

From : 
Congrats on merging your first pull request!
`![proud](https://github.com/shreeshailaya/C-DAC-Notes/blob/main/Media/proud_of.gif)`

To : 
Congrats on merging your first pull request!
Thank you for your valuable Contribution.
please fill out the following form for further reference.
https://forms.gle/F6vkGHBCVNLvVBsm8
`![proud](https://github.com/shreeshailaya/C-DAC-Notes/blob/main/Media/proud_of.gif)`

**Comment by readysetlearn** [comment]
@shreeshailaya I can do this. Can you please assign the issue to me?
