### ISSUE TITLE
Modify main Readme.md file to add Python and Django into it

### ISSUE THREAD

**Issue by shreeshailaya** [shreeshailaya/C-DAC-Notes#182]
Modify the main Readme.md file add Python and Django columns into the table just below `Welcome to CDAC Notes` 

Add the same topic like below with there emojis and add there respective index links into readme.md :
☕ Core Java
💾 Database Technologies

Feel free to ask any further questions.

**Comment by larrikin-coder** [comment]
@shreeshailaya please assign me with this issue.

**Comment by larrikin-coder** [comment]
where are the index links? In the repo?

**Comment by larrikin-coder** [comment]
@shreeshailaya please accept my PR

**Comment by techieadi4703** [comment]
hey @shreeshailaya , I'm interested in this issue can you assign me this issue to me.
