### ISSUE TITLE
Day1 OS documentation 

### ISSUE THREAD

**Issue by shreeshailaya** [shreeshailaya/C-DAC-Notes#22]
Documentation pending few[ points reamining ](https://github.com/shreeshailaya/c-dac/tree/main/Operating%20system#day-1-17)

**Comment by ShikhaDhiman1** [comment]
What are we supposed to do in this?

**Comment by ShikhaDhiman1** [comment]
I want to work on this issue. Can you please elaborate on this issue

**Comment by shreeshailaya** [comment]
@ShikhaDhiman1 please check other issues this is resolved already

**Comment by ShikhaDhiman1** [comment]
@shreeshailaya thanks. I will go for another ones.

**Comment by ShikhaDhiman1** [comment]
@shreeshailaya thanks. I will go for other ones.
