### ISSUE TITLE
23/7 day 8 HTML DOM assignments incomplete

### ISSUE THREAD

**Issue by shreeshailaya** [shreeshailaya/C-DAC-Notes#47]
[HTML DOM ASSIGNMENTS REAMINING ](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Web%20Programming/23-7-d8)

**Comment by vismitap** [comment]
Hey, I would like to work on this issue! Could you please tell what needs to be done here exactly? Do we need to provide solutions to the questions in the assignment?

**Comment by shreeshailaya** [comment]
yes, you need to provide the solution [DOM Manipulation ](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Web%20Programming/23-7-d8/DOM%20Manipulation-1) is done now you need to create a new folder called HTML DOM and do the assignments mention in it.

**Comment by vismitap** [comment]
Is this naming convention okay?

![image](https://user-images.githubusercontent.com/47056243/135848055-13ac58c2-6a71-42af-a5a4-43887c514952.png)

**Comment by vismitap** [comment]
> yes just put it in one folder called HTML DOM.

in the root?

**Comment by shreeshailaya** [comment]
here in[ Web Programming/23-7d8](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Web%20Programming/23-7-d8)

> > yes just put it in one folder called HTML DOM.
> 
> in the root? Or in web programming?
