### ISSUE TITLE
Operators in Java

### ISSUE THREAD

**Issue by barunipriyats** [shreeshailaya/C-DAC-Notes#67]
@shreeshailaya I would like to contribute some programs related to the topic - operators in Java. I am good in Java as I did a few mini-projects in it. I request you to assign this task to me.

**Comment by barunipriyats** [comment]
@shreeshailaya Please assign this issue to me under the hacktoberfest tag.

**Comment by shreeshailaya** [comment]
@barunipriyats Here are some issues #36 #11 #10 which are related to core java  #14 DS in java so make a request on one of them, else see the [core java](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Core%20Java),[DS](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Data%20structure) and [Advanced Java](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Advanced%20Java) find the issues create them with reference link and I will able to assign it to you.
