### ISSUE TITLE
Complete the Data Strecture Readme.md Notes Day14 

### ISSUE THREAD

**Issue by shreeshailaya** [shreeshailaya/C-DAC-Notes#94]
here are the notes on Data structure [day 14](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Data%20structure#day-14-17hashtime-complixitykruskal-algorithmprimes-algoavl-tree-balanced-factor) need to complete them according to other days refer to other days in the same file if you want to use any media(image/png/gif) keep them in [C-DAC-Notes/Data structure/Media/](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Data%20structure/Media).

Note: Use code snippets they should be in java.

**Comment by shilpeegupta14** [comment]
hi, @shreeshailaya 
I would like to do this. Please assign this task to me.

**Comment by Blaize99** [comment]
i would like to contribute to this task. Please assign it to me

**Comment by Blaize99** [comment]
I have made the PR. Please verify
